# Generated by Django 3.1.7 on 2021-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='keywordstore',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
