# Generated by Django 3.1.7 on 2021-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210326_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordstore',
            name='key_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
